// Auto-generated by elevenlabs_batch_tts.py — do not edit manually.
// Source: audio_library.txt
// 37 clips, 91 total MP3 files.

#pragma once
#include <DFRobotDFPlayerMini.h>

// ── Clip identifiers ──────────────────────────────────────────────────────────
// Usage:
//   audio.play(AudioClip::BOMB_ALPHA_HAS_BEEN_PLANTED);
//   audio.playRandom(AudioClip::RED_TEAM_HAS_THE_HARDPOINT);
//
// Requires MP3s in the /MP3/ folder on the SD card.
// Uses playMp3Folder() — reliable filename-based playback, not FAT order.

enum class AudioClip : uint8_t {
    // Keycard Override
    THE_TERMINAL_IS_NEUTRAL                            = 0,  // 0001-0004  [neutral:female_nuke:clean] x4
    THE_TERMINAL_IS_CLAIMED_BY_THE_RED_TEAM            = 1,  // 0005-0008  [neutral:female_nuke:clean] x4
    THE_TERMINAL_IS_CLAIMED_BY_THE_BLUE_TEAM           = 2,  // 0009-0012  [neutral:female_nuke:clean] x4
    THE_TERMINAL_IS_CAPTURED_BY_THE_RED_TEAM           = 3,  // 0013-0016  [excited:female_nuke:clean] x4
    THE_TERMINAL_IS_CAPTURED_BY_THE_BLUE_TEAM          = 4,  // 0017-0020  [excited:female_nuke:clean] x4
    RED_TEAM_RUNS_THE_TERMINAL                         = 5,  // 0021-0024  [excited:female_nuke:clean] x4
    BLUE_TEAM_RUNS_THE_TERMINAL                        = 6,  // 0025-0028  [excited:female_nuke:clean] x4
    BOTH_TEAMS_ARE_TIED_FOR_THE_TERMINAL               = 7,  // 0029-0032  [neutral:female_nuke:clean] x4

    // Hardpoint / Domination
    RED_TEAM_HAS_THE_HARDPOINT                         = 8,  // 0033-0035  [excited:andy_military:clean] x3
    BLUE_TEAM_HAS_THE_HARDPOINT                        = 9,  // 0036-0038  [excited:andy_military:clean] x3
    RED_TEAM_IS_IN_THE_LEAD                            = 10,  // 0039-0041  [excited:own_ut_guy:clean] x3
    BLUE_TEAM_IS_IN_THE_LEAD                           = 11,  // 0042-0044  [excited:own_ut_guy:clean] x3

    // Bomb
    BOMB_ALPHA_HAS_BEEN_PLANTED                        = 12,  // 0045-0047  [urgent:andy_military:radio] x3
    BOMB_BRAVO_HAS_BEEN_PLANTED                        = 13,  // 0048-0050  [urgent:andy_military:radio] x3
    BOMB_CHARLIE_HAS_BEEN_PLANTED                      = 14,  // 0051-0053  [urgent:andy_military:radio] x3
    THE_BOMB_IS_ARMED_I_REPEAT_THE_BOMB_IS_ARMED       = 15,  // 0054-0056  [excited:andy_military:radio] x3
    FIVE_MINUTES_TO_DETONATION                         = 16,  // 0057-0059  [excited:andy_military:radio] x3
    FOUR_MINUTES_TO_DETONATION                         = 17,  // 0060-0062  [excited:andy_military:radio] x3
    THREE_MINUTES_TO_DETONATION                        = 18,  // 0063-0065  [excited:andy_military:radio] x3
    TWO_MINUTES_TO_DETONATION                          = 19,  // 0066-0068  [excited:andy_military:radio] x3
    ONE_MINUTE_TO_DETONATION                           = 20,  // 0069-0071  [excited:andy_military:radio] x3
    THIRTY_SECONDS_TO_DETONATION                       = 21,  // 0072-0074  [excited:andy_military:radio] x3
    TEN_SECONDS_TO_DETONATION                          = 22,  // 0075-0077  [excited:andy_military:radio] x3
    BOMD_CHARGED_TO_10_PERCENT_I_REPEAT_BOMB_CHARGED_TO_10_PERCENT = 23,  // 0078  [excited:andy_military:radio]
    BOMD_CHARGED_TO_20_PERCENT_I_REPEAT_BOMB_CHARGED_TO_20_PERCENT = 24,  // 0079  [excited:andy_military:radio]
    BOMD_CHARGED_TO_30_PERCENT_I_REPEAT_BOMB_CHARGED_TO_30_PERCENT = 25,  // 0080  [excited:andy_military:radio]
    BOMD_CHARGED_TO_40_PERCENT_I_REPEAT_BOMB_CHARGED_TO_40_PERCENT = 26,  // 0081  [excited:andy_military:radio]
    BOMD_CHARGED_TO_50_PERCENT_I_REPEAT_BOMB_CHARGED_TO_50_PERCENT = 27,  // 0082  [excited:andy_military:radio]
    BOMD_CHARGED_TO_60_PERCENT_I_REPEAT_BOMB_CHARGED_TO_60_PERCENT = 28,  // 0083  [excited:andy_military:radio]
    BOMD_CHARGED_TO_70_PERCENT_I_REPEAT_BOMB_CHARGED_TO_70_PERCENT = 29,  // 0084  [excited:andy_military:radio]
    BOMD_CHARGED_TO_80_PERCENT_I_REPEAT_BOMB_CHARGED_TO_80_PERCENT = 30,  // 0085  [excited:andy_military:radio]
    BOMD_CHARGED_TO_90_PERCENT_I_REPEAT_BOMB_CHARGED_TO_90_PERCENT = 31,  // 0086  [excited:andy_military:radio]
    BOMD_WILL_DETONATE                                 = 32,  // 0087  [excited:andy_military:radio]
    BOMB_IS_BEING_DEFUSED                              = 33,  // 0088  [excited:andy_military:radio]
    DEFUSAL_ATTEMPT_CANCELLED                          = 34,  // 0089  [excited:andy_military:radio]
    BOMB_HAS_DETONATED_THE_BOMB_HAS_DETONATED_THE_ATTACKING_TEAM_WINS = 35,  // 0090  [excited:andy_military:radio]
    BOMB_HAS_BEEN_DEFUSED_THE_BOMB_HAS_BEEN_DEFUSED_THE_DEFENDING_TEAM_WINS = 36,  // 0091  [excited:andy_military:radio]

    _COUNT  // sentinel — keep last
};

// ── Internal lookup tables ────────────────────────────────────────────────────
static const uint16_t _AUDIO_BASE[37]     = {1, 5, 9, 13, 17, 21, 25, 29, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91};
static const uint8_t  _AUDIO_VARIANTS[37] = {4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

// ── AirsoftAudio class ────────────────────────────────────────────────────────
class AirsoftAudio {
public:
    explicit AirsoftAudio(DFRobotDFPlayerMini& player) : _player(player) {}

    // Play the first (or only) variant of a clip
    void play(AudioClip clip) {
        _player.playMp3Folder(_AUDIO_BASE[(uint8_t)clip]);
    }

    // Play a random variant — identical to play() for clips with only 1 variant
    void playRandom(AudioClip clip) {
        uint8_t idx = (uint8_t)clip;
        _player.playMp3Folder(_AUDIO_BASE[idx] + random(_AUDIO_VARIANTS[idx]));
    }

private:
    DFRobotDFPlayerMini& _player;
};
