/**
 * Keycard Override — ESP32 RFID objective box firmware
 *
 * Hardware:
 *   ESP32-WROOM-32 (30 pin)
 *   RC522 RFID reader (SPI)
 *   WS2812B LED strip
 *   TM1637 6-digit display (digits 0-2 = red team, digits 3-5 = blue team)
 *
 * Libraries (install via Arduino Library Manager):
 *   RFID_MFRC522v2    by GithubCommunity
 *   FastLED           by Daniel Garcia
 *   TM1637TinyDisplay by AKJ7
 *
 * Game flow:
 *   1. Neutral (yellow). Either team can claim.
 *   2. Hold claim card 5s → objective claimed (bar breathes team color).
 *   3. Hold capture card 5s → bar fills → +1 point → back to neutral.
 *   4. Claim times out after 20s with no capture → back to neutral.
 *   5. Opposing claim card held 5s → bar sweeps to new team color → claimed by them.
 *   6. Card removed mid-claim or mid-capture → action cancelled.
 */

#include <SPI.h>
#include <MFRC522v2.h>
#include <MFRC522DriverSPI.h>
#include <MFRC522DriverPinSimple.h>
#include <FastLED.h>
#include <TM1637TinyDisplay6.h>

// ═══════════════════════════════════════════════════════════
//  SETTINGS
// ═══════════════════════════════════════════════════════════
#define CAPTURE_SECS       5      // seconds capture card must be held (= 1 point)
#define POST_SCORE_SECS    8      // celebration lock after scoring
#define CLAIM_SECS         5      // seconds claim card must be held to claim objective
#define NUM_LEDS          16      // WS2812 LED count
#define LED_BRIGHTNESS   100      // 0-255
#define CARD_TIMEOUT_MS  700      // ms card can be absent before action cancels
#define POLL_INTERVAL_MS 100      // how often to check if held card is still present

// ═══════════════════════════════════════════════════════════
//  PINS
// ═══════════════════════════════════════════════════════════
#define PIN_RC522_SS        5
#define PIN_RC522_RST      22
#define PIN_LED             4
#define PIN_DISP_CLK       26
#define PIN_DISP_DIO       27

// ═══════════════════════════════════════════════════════════
//  CARD UIDs — generated by CardScanner, saved as cards.h
// ═══════════════════════════════════════════════════════════
#include "cards.h"

// ═══════════════════════════════════════════════════════════
//  OBJECTS
// ═══════════════════════════════════════════════════════════
MFRC522DriverPinSimple ss_pin(PIN_RC522_SS);
MFRC522DriverSPI       rfidDriver{ss_pin, SPI, SPISettings(1000000u, MSBFIRST, SPI_MODE0)};
MFRC522                rfid{rfidDriver};
CRGB                   leds[NUM_LEDS];
TM1637TinyDisplay6     disp(PIN_DISP_CLK, PIN_DISP_DIO);

// ═══════════════════════════════════════════════════════════
//  STATE
// ═══════════════════════════════════════════════════════════
enum State {
  NEUTRAL,
  CLAIMED_RED,       // objective claimed by red — red can now capture
  CLAIMED_BLUE,      // objective claimed by blue — blue can now capture
  RED_CAPTURING,     // red's capture bar is filling
  BLUE_CAPTURING,    // blue's capture bar is filling
  CLAIMING,          // a team is claiming the objective
  POST_SCORE         // brief celebration after scoring
};

State         gameState        = NEUTRAL;
uint8_t       redScore         = 0;
uint8_t       blueScore        = 0;
uint8_t       lastScorer       = 0;     // 1=red, 2=blue
uint8_t       claimingToTeam   = 0;     // 1=red claiming, 2=blue claiming
uint8_t       claimingFromTeam = 0;     // 0=yellow, 1=red, 2=blue
unsigned long phaseStart       = 0;
unsigned long lastCardMillis   = 0;
unsigned long lastPollTime     = 0;

byte          heldUID[10]      = {};
byte          heldUIDLen       = 0;
unsigned long lastCardSeen     = 0;

const CRGB COL_YELLOW = CRGB(255, 160,   0);
const CRGB COL_RED    = CRGB(255,   0,   0);
const CRGB COL_BLUE   = CRGB(  0,   0, 255);

// ═══════════════════════════════════════════════════════════
//  CARD HELPERS
// ═══════════════════════════════════════════════════════════
bool cardMatch(const CardDef& c) {
  if (rfid.uid.size != c.len) return false;
  return memcmp(rfid.uid.uidByte, c.uid, c.len) == 0;
}

template<size_t N>
bool cardMatchAny(const CardDef (&list)[N]) {
  for (size_t i = 0; i < N; i++)
    if (cardMatch(list[i])) return true;
  return false;
}

void saveHeld() {
  memcpy(heldUID, rfid.uid.uidByte, rfid.uid.size);
  heldUIDLen   = rfid.uid.size;
  lastCardSeen = millis();
  rfid.PICC_HaltA();
  rfid.PCD_StopCrypto1();
}

bool pollHeldCard() {
  byte atqa[2]; byte sz = sizeof(atqa);
  MFRC522::StatusCode r = rfid.PICC_WakeupA(atqa, &sz);
  if (r != MFRC522Constants::STATUS_OK && r != MFRC522Constants::STATUS_COLLISION) return false;
  if (!rfid.PICC_ReadCardSerial()) return false;
  bool match = (rfid.uid.size == heldUIDLen &&
                memcmp(rfid.uid.uidByte, heldUID, heldUIDLen) == 0);
  rfid.PICC_HaltA();
  rfid.PCD_StopCrypto1();
  return match;
}

// ═══════════════════════════════════════════════════════════
//  LEDs
// ═══════════════════════════════════════════════════════════
void updateLEDs() {
  unsigned long elapsed = millis() - phaseStart;

  switch (gameState) {

    case NEUTRAL: {
      uint8_t bri = beatsin8(20, 5, 220);
      fill_solid(leds, NUM_LEDS, CRGB(
        (uint16_t)COL_YELLOW.r * bri / 255,
        (uint16_t)COL_YELLOW.g * bri / 255,
        0
      ));
      break;
    }

    case CLAIMED_RED: {
      uint8_t bri = beatsin8(30, 5, 220);
      fill_solid(leds, NUM_LEDS, CRGB(bri, 0, 0));
      break;
    }

    case CLAIMED_BLUE: {
      uint8_t bri = beatsin8(30, 5, 220);
      fill_solid(leds, NUM_LEDS, CRGB(0, 0, bri));
      break;
    }

    case RED_CAPTURING:
    case BLUE_CAPTURING: {
      CRGB teamCol = (gameState == RED_CAPTURING) ? COL_RED : COL_BLUE;
      uint8_t lit  = (uint8_t)min((unsigned long)NUM_LEDS,
        elapsed * NUM_LEDS / ((unsigned long)CAPTURE_SECS * 1000));
      uint8_t sparkBri = beatsin8(90, 0, 255);
      for (int i = 0; i < NUM_LEDS; i++) {
        if (i < lit)        leds[i] = teamCol;
        else if (i == lit)  leds[i] = teamCol.scale8(sparkBri);
        else                leds[i] = CRGB::Black;
      }
      break;
    }

    case CLAIMING: {
      CRGB newCol = (claimingToTeam   == 1) ? COL_RED  : COL_BLUE;
      CRGB oldCol = (claimingFromTeam == 1) ? COL_RED  :
                    (claimingFromTeam == 2) ? COL_BLUE : COL_YELLOW;
      uint8_t lit = (uint8_t)min((unsigned long)NUM_LEDS,
        elapsed * NUM_LEDS / ((unsigned long)CLAIM_SECS * 1000));
      for (int i = 0; i < NUM_LEDS; i++)
        leds[i] = (i < lit) ? newCol : oldCol;
      break;
    }

    case POST_SCORE: {
      CRGB col = (lastScorer == 1) ? COL_RED : COL_BLUE;
      bool on  = (elapsed / 150) % 2 == 0;
      fill_solid(leds, NUM_LEDS, on ? col : CRGB::Black);
      break;
    }
  }

  FastLED.show();
}

// ═══════════════════════════════════════════════════════════
//  DISPLAY — digits 0-2 = red score, digits 3-5 = blue score
// ═══════════════════════════════════════════════════════════
void updateDisplays() {
  disp.showNumber(redScore,  true, 3, 0);
  disp.showNumber(blueScore, true, 3, 3);
}

// ═══════════════════════════════════════════════════════════
//  GAME LOGIC
// ═══════════════════════════════════════════════════════════
void scorePoint(uint8_t team) {
  if (team == 1) redScore++;
  else           blueScore++;
  lastScorer = team;
  heldUIDLen = 0;
  phaseStart = millis();
  gameState  = POST_SCORE;
}

void startClaim(uint8_t toTeam) {
  if      (gameState == CLAIMED_RED   || gameState == RED_CAPTURING)  claimingFromTeam = 1;
  else if (gameState == CLAIMED_BLUE  || gameState == BLUE_CAPTURING) claimingFromTeam = 2;
  else                                                                 claimingFromTeam = 0;
  claimingToTeam = toTeam;
  phaseStart     = millis();
  gameState      = CLAIMING;
  saveHeld();
}

void resetGame() {
  redScore   = 0;
  blueScore  = 0;
  lastScorer = 0;
  heldUIDLen = 0;
  phaseStart = millis();
  gameState  = NEUTRAL;
}

void handleCard() {
  unsigned long now = millis();
  if (now - lastCardMillis < 500) return;
  lastCardMillis = now;

  if (cardMatchAny(ADMIN_CARDS)) { resetGame(); return; }

  switch (gameState) {

    case NEUTRAL:
      if      (cardMatchAny(RED_CLAIM_CARDS))  startClaim(1);
      else if (cardMatchAny(BLUE_CLAIM_CARDS)) startClaim(2);
      break;

    case CLAIMED_RED:
      if (cardMatchAny(RED_CAPTURE_CARDS)) {
        gameState  = RED_CAPTURING;
        phaseStart = now;
        saveHeld();
      } else if (cardMatchAny(BLUE_CLAIM_CARDS)) {
        startClaim(2);
      }
      break;

    case CLAIMED_BLUE:
      if (cardMatchAny(BLUE_CAPTURE_CARDS)) {
        gameState  = BLUE_CAPTURING;
        phaseStart = now;
        saveHeld();
      } else if (cardMatchAny(RED_CLAIM_CARDS)) {
        startClaim(1);
      }
      break;

    case RED_CAPTURING:
      if (cardMatchAny(BLUE_CLAIM_CARDS)) startClaim(2);
      break;

    case BLUE_CAPTURING:
      if (cardMatchAny(RED_CLAIM_CARDS)) startClaim(1);
      break;

    default:
      break;
  }
}

// ═══════════════════════════════════════════════════════════
//  SETUP & LOOP
// ═══════════════════════════════════════════════════════════
void setup() {
  Serial.begin(115200);

  SPI.begin();
  pinMode(PIN_RC522_RST, OUTPUT);
  digitalWrite(PIN_RC522_RST, HIGH);
  delay(10);
  rfid.PCD_Init();

  FastLED.addLeds<WS2812, PIN_LED, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(LED_BRIGHTNESS);

  disp.begin();
  disp.setBrightness(BRIGHT_HIGH);

  // Hardware test
  Serial.println("Hardware test...");
  disp.showNumber(888888);
  fill_solid(leds, NUM_LEDS, CRGB::Red);   FastLED.show(); delay(500);
  fill_solid(leds, NUM_LEDS, CRGB::Green); FastLED.show(); delay(500);
  fill_solid(leds, NUM_LEDS, CRGB::Blue);  FastLED.show(); delay(500);
  fill_solid(leds, NUM_LEDS, CRGB::Black); FastLED.show();
  disp.clear();
  Serial.println("Hardware test done.");

  resetGame();
  Serial.println("Keycard Override — ready.");
}

void loop() {
  unsigned long now      = millis();
  bool holdState = (gameState == CLAIMING      ||
                    gameState == RED_CAPTURING ||
                    gameState == BLUE_CAPTURING);

  // ── Card hold tracking ───────────────────────────────────
  if (holdState && now - lastPollTime >= POLL_INTERVAL_MS) {
    lastPollTime = now;
    if (pollHeldCard()) {
      lastCardSeen = now;
    } else if (now - lastCardSeen > CARD_TIMEOUT_MS) {
      if (gameState == CLAIMING) {
        if      (claimingFromTeam == 1) gameState = CLAIMED_RED;
        else if (claimingFromTeam == 2) gameState = CLAIMED_BLUE;
        else                            gameState = NEUTRAL;
      } else if (gameState == RED_CAPTURING) {
        gameState  = CLAIMED_RED;
      } else {
        gameState  = CLAIMED_BLUE;
      }
      phaseStart = now;
      heldUIDLen = 0;
    }
  }

  // ── Claim complete → claimed ─────────────────────────────
  if (gameState == CLAIMING &&
      now - phaseStart >= (unsigned long)CLAIM_SECS * 1000) {
    gameState  = (claimingToTeam == 1) ? CLAIMED_RED : CLAIMED_BLUE;
    phaseStart = now;
    heldUIDLen = 0;
  }

  // ── Capture complete → score ─────────────────────────────
  if ((gameState == RED_CAPTURING || gameState == BLUE_CAPTURING) &&
      now - phaseStart >= (unsigned long)CAPTURE_SECS * 1000)
    scorePoint(gameState == RED_CAPTURING ? 1 : 2);

  // ── Post-score → neutral ─────────────────────────────────
  if (gameState == POST_SCORE &&
      now - phaseStart >= (unsigned long)POST_SCORE_SECS * 1000) {
    gameState  = NEUTRAL;
    phaseStart = now;
  }

  // ── New card scan (only when not holding) ────────────────
  if (!holdState) {
    if (rfid.PICC_IsNewCardPresent() && rfid.PICC_ReadCardSerial()) {
      handleCard();
      if (heldUIDLen == 0) {
        rfid.PICC_HaltA();
        rfid.PCD_StopCrypto1();
      }
    }
  }

  updateLEDs();
  updateDisplays();
}
